functionsDirectory = "C:\\Users\\djkra\\Desktop\\TKFM_RECORDS_V3\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
edge_functions = "C:\\Users\\djkra\\Desktop\\TKFM_RECORDS_V3\\netlify\\edge-functions"
publish = "C:\\Users\\djkra\\Desktop\\TKFM_RECORDS_V3"
publishOrigin = "config"
functions = "C:\\Users\\djkra\\Desktop\\TKFM_RECORDS_V3\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[edge_functions]]
function = "lockdown"
path = "/admin/*"

[[edge_functions]]
function = "lockdown"
path = "/owner/*"

[[edge_functions]]
function = "lockdown"
path = "/secure/*"

[[edge_functions]]
function = "lockdown"
path = "/private/*"

[[edge_functions]]
function = "lockdown"
path = "/.netlify/*"

[functions]

[functions."*"]