functionsDirectory = "C:\\Users\\djkra\\Desktop\\TKFM_RECORDS_V3\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
edge_functions = "C:\\Users\\djkra\\Desktop\\TKFM_RECORDS_V3\\netlify\\edge-functions"
publish = "C:\\Users\\djkra\\Desktop\\TKFM_RECORDS_V3"
publishOrigin = "config"
functions = "C:\\Users\\djkra\\Desktop\\TKFM_RECORDS_V3\\netlify\\functions"

[build.environment]
NODE_VERSION = "22"
NODE_ENV = "production"
DEBUG_MODE = "false"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[scheduled]]
path = "/.netlify/functions/tkfm-master-cron"
schedule = "*/1 * * * *"

[[edge_functions]]
function = "lockdown"
path = "/admin/*"

[[edge_functions]]
function = "lockdown"
path = "/owner/*"

[[edge_functions]]
function = "lockdown"
path = "/secure/*"

[[edge_functions]]
function = "lockdown"
path = "/private/*"

[[edge_functions]]
function = "lockdown"
path = "/.netlify/*"

[functions]

[functions.timeout]
seconds = 26.0

[functions."*"]
included_files = ["netlify/functions/_middleware-secret-guard.js"]
external_node_modules = ["stripe", "jsonwebtoken", "bcryptjs", "@supabase/supabase-js", "ethers", "ioredis", "cloudinary", "pdfkit", "@aws-sdk/client-s3", "@apollo/server"]
node_bundler = "esbuild"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/stripe-webhook"
to = "/.netlify/functions/stripe-webhook-ledger"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]