[build]
  publish = "."
  functions = "netlify/functions"

[[edge_functions]]
  function = "lockdown"
  path = "/admin/*"

[[edge_functions]]
  function = "lockdown"
  path = "/owner/*"

[[edge_functions]]
  function = "lockdown"
  path = "/secure/*"

[[edge_functions]]
  function = "lockdown"
  path = "/private/*"

[[edge_functions]]
  function = "lockdown"
  path = "/.netlify/*"
