[versions]
core = "1.12.0"
activity = "1.7.2"
splashscreen = "1.0.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
